#!/bin/bash
source ./common.sh
check_root

echo "Please enter root password to setup"
read -s MYSQL_ROOT_PASSWORD

dnf install mysql-server -y
VALIDATE $? "Installing MySQL Server"

systemctl enable mysqld &>>$LOG_FILE
VALIDATE $? "Enabling MySQL Service"

systemctl start mysqld &>>$LOG_FILE
VALIDATE $? "Starting MySQL Service"

# Get the temporary password generated by MySQL
mysql_secure_installation --set-root-pass RoboShop@1 &>>$LOG_FILE
VALIDATE $? "Setting up MySQL root password"

print_time
